### ISSUE TITLE
All this string handling functions duplicate the error handling code

### ISSUE THREAD

**Issue by Hugoargui** [Hugoargui/rust#3]
https://github.com/Hugoargui/rust/blob/fddab33bcffa816ab562ba50ca9932c942bb086a/homework3/src/stringlib.rs#L40

All this functions have the same "if valid_string() return OK, otherwise return Error("Empty or broken string")

It's not soooo horrible, but isn't there a better way to structure the code to avoid this? 

**Is it common place to use strategy patterns or similar in rust?** 

I'm thinking something like:

`process_string(input_string : String, stringOperation : function) `

and then the run function just calls the same one process_string() with different lambdas depending on the option chosen by the user.

**Comment by luciusmagn** [comment]
Yeah, you can use a strategy pattern in Rust no problem, you could but you could also make valid_string return `Result<(), Box<dyn Error>>` and do `valid_string(...)?;` at the top of your operation functions, which is also very simple

**Comment by Hugoargui** [comment]
ok thanks! 
I need to get used to the foo(...)?; syntax and use it more... it's different from the "?" I'm used to from other languages 😄
