### ISSUE TITLE
Is suppressing (clippy::needless_return) warning good practice? 

### ISSUE THREAD

**Issue by Hugoargui** [Hugoargui/rust#4]
https://github.com/Hugoargui/rust/blob/fddab33bcffa816ab562ba50ca9932c942bb086a/homework3/src/user_input.rs#L16

I know this is not an early return, and rust being an expression based language, in theory different branches of the if should just return implicitly by removing the "return" keyword and the ";".

I totally get it for short branches. 

But in this more complicated case, removing the return makes it really hard to mentally parse it for me when I'm reading. I guess I'd get used to it with time by reading a lot of rust. 

So my question is, is it the rustacean way to remove returns even in such a complex branch, or should I just suck it up and get used to it?

Also, clippy seems quite opinionated, is it common to suppress it's warnings in certain situations, or is it a bad practice I should get rid of?

**Comment by luciusmagn** [comment]
Sadly, the good practice here is to just get used to it. It takes a while, I know it took me a while, but you will get used to not using return needlessly ://

**Comment by Hugoargui** [comment]
yeah I was expecting that answer 😆 thanks!
