### ISSUE TITLE
Minor HW3 feedback

### ISSUE THREAD

**Issue by luciusmagn** [Hugoargui/rust#6]
https://github.com/Hugoargui/rust/blob/5139d29f01784ea3a7aff7f5f2f3e5556bacc19c/homework3/src/stringlib.rs#L1

This is non-standard and typically only used when the source code of the module is generated from something, such as a protobuf compiler (those files should by convention be located in a special folder that Cargo gives you the path of)

You can just make it a proper submodule, or declare it the submodule of main.rs/lib.rs and import it via `use crate::csv_lib;`

Also a minor nit-pick is to be consisted with naming: `stringlib vs csv_lib` :D

**Comment by Hugoargui** [comment]
👍
